"""Paper experiment configuration kept separate from Phase 2 defaults."""

NUM_CLIENTS = 50
CLIENTS_PER_ROUND = 10
DIRICHLET_BETA = 0.1
MIN_SAMPLES_PER_CLIENT = 10
NUM_ROUNDS = 200
LOCAL_EPOCHS = 2
BATCH_SIZE = 64
LEARNING_RATE = 0.001
WEIGHT_DECAY = 0.0
PATCH_SIZE = 4
MASK_RATIO = 0.8
EMBEDDING_DIM = 128
MAE_WEIGHT = 0.7
PROTO_WEIGHT = 0.3
SCHEDULER_FACTOR = 0.1
SCHEDULER_PATIENCE = 5
RANDOM_SEED = 42
LABEL_FRACTION = 0.01
DEVICE = "cuda"  # callers must fall back to CPU when unavailable
CHECKPOINT_FREQUENCY = 10
LOG_DIR = "results/flame"
